services:
  frontend:
    build:
      context: "../IDCardFrontend"
    image: idfrontend:latest
    ports:
      - '8080:3000'
    restart: always
    environment:
      - NODE_EN=preprod
      - PORT=3000